### ISSUE TITLE
[suggestion] Organizational dossier feature

### ISSUE THREAD

**Issue by thesle3p** [jadekeys/HINTS#3]
Just a suggestion but it might be nice to make a feature or a fork of this tool to gather information on a target organization instead of an individual for datapoints like Locations,Credit and financial info,known vendors etc. Maybe even an option to generate dossiers on physical locations as well.

**Comment by jadekeys** [comment]
Thanks for the idea! I plan on revamping this in the near future, and will likely add that in.
